apiVersion: v1
kind: Service
metadata:
  name: pgsql-np-dotnet
  labels:
    app: postgres-dotnet
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30007
  selector:
    app: postgres-dotnet