// <auto-generated />
using System;
using Infraestructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(IdealCityDbContext))]
    partial class IdealCityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CityUser", b =>
                {
                    b.Property<Guid>("FavouriteCitiesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FavouritedByUsersId")
                        .HasColumnType("uuid");

                    b.HasKey("FavouriteCitiesId", "FavouritedByUsersId");

                    b.HasIndex("FavouritedByUsersId");

                    b.ToTable("CityUser");
                });

            modelBuilder.Entity("Domain.CityAggregate.City", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities", (string)null);
                });

            modelBuilder.Entity("Domain.CountryAggregate.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Countries", (string)null);
                });

            modelBuilder.Entity("Domain.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("CityId");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProfilePicture")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CityUser", b =>
                {
                    b.HasOne("Domain.CityAggregate.City", null)
                        .WithMany()
                        .HasForeignKey("FavouriteCitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("FavouritedByUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.CityAggregate.City", b =>
                {
                    b.HasOne("Domain.CountryAggregate.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.Cities.Weather", "Weather", b1 =>
                        {
                            b1.Property<Guid>("CityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AverageTemperature")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("AverageTemperature");

                            b1.HasKey("CityId");

                            b1.ToTable("Cities");

                            b1.WithOwner()
                                .HasForeignKey("CityId");
                        });

                    b.OwnsMany("Domain.City.ValueObjects.CityReview", "Reviews", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("CityReviewId");

                            b1.Property<Guid>("CityId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Rating")
                                .HasColumnType("int");

                            b1.Property<string>("Review")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.HasKey("Id", "CityId");

                            b1.HasIndex("CityId");

                            b1.ToTable("CityReviews", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CityId");
                        });

                    b.OwnsMany("Domain.City.ValueObjects.CityReviewId", "ReviewsIds", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("CityId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("ReviewId");

                            b1.HasKey("Id");

                            b1.HasIndex("CityId");

                            b1.ToTable("CityReviewIds", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CityId");
                        });

                    b.OwnsOne("Domain.City.ValueObjects.Indicator", "Indicators", b1 =>
                        {
                            b1.Property<Guid>("CityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AverageMonthlyNetSalary")
                                .HasColumnType("text")
                                .HasColumnName("AverageMonthlyNetSalary");

                            b1.Property<string>("CostIndex")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("CostIndex");

                            b1.Property<string>("Gasoline")
                                .HasColumnType("text")
                                .HasColumnName("Gasoline");

                            b1.Property<string>("PublicTransportationIndex")
                                .HasColumnType("text")
                                .HasColumnName("PublicTransportationIndex");

                            b1.HasKey("CityId");

                            b1.ToTable("Cities");

                            b1.WithOwner()
                                .HasForeignKey("CityId");
                        });

                    b.OwnsOne("Domain.Common.ValueObjects.AverageRating", "AverageRating", b1 =>
                        {
                            b1.Property<Guid>("CityId")
                                .HasColumnType("uuid");

                            b1.Property<int>("TotalRatings")
                                .HasColumnType("integer")
                                .HasColumnName("AverageRatingTotalRatings");

                            b1.Property<double>("Value")
                                .HasColumnType("double precision")
                                .HasColumnName("AverageRatingValue");

                            b1.HasKey("CityId");

                            b1.ToTable("Cities");

                            b1.WithOwner()
                                .HasForeignKey("CityId");
                        });

                    b.Navigation("AverageRating");

                    b.Navigation("Country");

                    b.Navigation("Indicators");

                    b.Navigation("Reviews");

                    b.Navigation("ReviewsIds");

                    b.Navigation("Weather");
                });

            modelBuilder.Entity("Domain.CountryAggregate.Country", b =>
                {
                    b.OwnsMany("Domain.City.ValueObjects.CityId", "CityIds", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("CountryId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("CityId");

                            b1.HasKey("Id");

                            b1.HasIndex("CountryId");

                            b1.ToTable("CountryCitiesIds", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CountryId");
                        });

                    b.Navigation("CityIds");
                });

            modelBuilder.Entity("Domain.UserAggregate.User", b =>
                {
                    b.HasOne("Domain.CityAggregate.City", "City")
                        .WithMany("Users")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("Domain.User.ValueObject.Subscription", "Subscription", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("ExpirationDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ExpirationDate");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("boolean");

                            b1.Property<int>("SubscriptionType")
                                .HasColumnType("integer")
                                .HasColumnName("SubscriptionType");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("City");

                    b.Navigation("Subscription")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.CityAggregate.City", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.CountryAggregate.Country", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
